# Generated by Django 5.0.1 on 2025-05-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Space', 'Space'), ('Astronomy', 'Astronomy'), ('News', 'News'), ('Technology', 'Technology'), ('Physics', 'Physics'), ('Exploration', 'Exploration')], max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.tag'),
        ),
    ]
