# Generated by Django 5.0.1 on 2025-05-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
